name: push

on:
  push:
    branches:
      - '**'
      - '!develop'
      - '!main'

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      npm-cache-dir-path: ${{ steps.npm-cache-dir-path.outputs.dir }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '21.x'

      - name: Get npm cache directory path
        id: npm-cache-dir-path
        run: echo "dir=$(npm cache dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.npm-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - run: npm ci

  lint:
    runs-on: ubuntu-latest
    needs: setup
    defaults:
      run:
        working-directory: genesis
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ needs.setup.outputs.npm-cache-dir-path }}
          key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - run: npm ci
      - run: npm run prettier
      - run: npm run stylelint
      - run: npm run lint:quiet
      - run: npm run typecheck

  build:
    runs-on: ubuntu-latest
    needs: [setup, lint, test]
    defaults:
      run:
        working-directory: genesis
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ needs.setup.outputs.npm-cache-dir-path }}
          key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - run: npm ci
      - name: Build
        run: npm run build
